# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.visualize_Layout = QtWidgets.QHBoxLayout()
        self.visualize_Layout.setObjectName("visualize_Layout")
        self.inputLayout = QtWidgets.QVBoxLayout()
        self.inputLayout.setObjectName("inputLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineImagePath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineImagePath.setObjectName("lineImagePath")
        self.gridLayout_5.addWidget(self.lineImagePath, 0, 1, 1, 1)
        self.btnSelectImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectImage.setObjectName("btnSelectImage")
        self.gridLayout_5.addWidget(self.btnSelectImage, 0, 0, 1, 1)
        self.inputLayout.addLayout(self.gridLayout_5)
        self.graphicsViewInput = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsViewInput.setObjectName("graphicsViewInput")
        self.inputLayout.addWidget(self.graphicsViewInput)
        self.visualize_Layout.addLayout(self.inputLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.visualize_Layout.addWidget(self.line)
        self.outputLayout = QtWidgets.QVBoxLayout()
        self.outputLayout.setObjectName("outputLayout")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 0, 1, 1)
        self.btnRender = QtWidgets.QPushButton(self.centralwidget)
        self.btnRender.setObjectName("btnRender")
        self.gridLayout_6.addWidget(self.btnRender, 0, 1, 1, 1)
        self.btnDownload = QtWidgets.QPushButton(self.centralwidget)
        self.btnDownload.setObjectName("btnDownload")
        self.gridLayout_6.addWidget(self.btnDownload, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 4, 1, 1)
        self.outputLayout.addLayout(self.gridLayout_6)
        self.graphicsViewOutput = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsViewOutput.setObjectName("graphicsViewOutput")
        self.outputLayout.addWidget(self.graphicsViewOutput)
        self.visualize_Layout.addLayout(self.outputLayout)
        self.visualize_Layout.setStretch(0, 1)
        self.visualize_Layout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.visualize_Layout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.setting_GridLayout = QtWidgets.QGridLayout()
        self.setting_GridLayout.setObjectName("setting_GridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 4, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 1, 6, 1, 1)
        self.cbbShape = QtWidgets.QComboBox(self.centralwidget)
        self.cbbShape.setEditable(False)
        self.cbbShape.setObjectName("cbbShape")
        self.gridLayout_2.addWidget(self.cbbShape, 0, 1, 1, 2)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_2.addWidget(self.horizontalSlider_2, 1, 5, 1, 1)
        self.sliderSize = QtWidgets.QSlider(self.centralwidget)
        self.sliderSize.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSize.setObjectName("sliderSize")
        self.gridLayout_2.addWidget(self.sliderSize, 1, 1, 1, 1)
        self.spinBoxSize = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxSize.setObjectName("spinBoxSize")
        self.gridLayout_2.addWidget(self.spinBoxSize, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 4, 1, 1)
        self.sliderMinThick = QtWidgets.QSlider(self.centralwidget)
        self.sliderMinThick.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMinThick.setObjectName("sliderMinThick")
        self.gridLayout_2.addWidget(self.sliderMinThick, 2, 1, 1, 1)
        self.sliderMaxThick = QtWidgets.QSlider(self.centralwidget)
        self.sliderMaxThick.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMaxThick.setObjectName("sliderMaxThick")
        self.gridLayout_2.addWidget(self.sliderMaxThick, 3, 1, 1, 1)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.gridLayout_2.addWidget(self.horizontalSlider_5, 2, 5, 1, 1)
        self.horizontalSlider_6 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.gridLayout_2.addWidget(self.horizontalSlider_6, 3, 5, 1, 1)
        self.spinBoxMinThick = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxMinThick.setObjectName("spinBoxMinThick")
        self.gridLayout_2.addWidget(self.spinBoxMinThick, 2, 2, 1, 1)
        self.spinBoxMaxThick = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxMaxThick.setObjectName("spinBoxMaxThick")
        self.gridLayout_2.addWidget(self.spinBoxMaxThick, 3, 2, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_2.addWidget(self.spinBox_5, 2, 6, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_2.addWidget(self.spinBox_6, 3, 6, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.raidoBtnBorderYes = QtWidgets.QRadioButton(self.centralwidget)
        self.raidoBtnBorderYes.setObjectName("raidoBtnBorderYes")
        self.horizontalLayout.addWidget(self.raidoBtnBorderYes)
        self.raidoBtnBorderNo = QtWidgets.QRadioButton(self.centralwidget)
        self.raidoBtnBorderNo.setObjectName("raidoBtnBorderNo")
        self.horizontalLayout.addWidget(self.raidoBtnBorderNo)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 5, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 4, 1, 1)
        self.setting_GridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.setting_GridLayout)
        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuDownload_Settings = QtWidgets.QMenu(self.menuSettings)
        self.menuDownload_Settings.setObjectName("menuDownload_Settings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDownloads = QtWidgets.QAction(MainWindow)
        self.actionDownloads.setObjectName("actionDownloads")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionBinary_STL = QtWidgets.QAction(MainWindow)
        self.actionBinary_STL.setObjectName("actionBinary_STL")
        self.actionASCII_STL = QtWidgets.QAction(MainWindow)
        self.actionASCII_STL.setObjectName("actionASCII_STL")
        self.actionModels_Setting = QtWidgets.QAction(MainWindow)
        self.actionModels_Setting.setObjectName("actionModels_Setting")
        self.actionImage_Settings = QtWidgets.QAction(MainWindow)
        self.actionImage_Settings.setObjectName("actionImage_Settings")
        self.actionBinary_STL_2 = QtWidgets.QAction(MainWindow)
        self.actionBinary_STL_2.setObjectName("actionBinary_STL_2")
        self.actionASCII_STL_2 = QtWidgets.QAction(MainWindow)
        self.actionASCII_STL_2.setObjectName("actionASCII_STL_2")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuDownload_Settings.addAction(self.actionBinary_STL_2)
        self.menuDownload_Settings.addAction(self.actionASCII_STL_2)
        self.menuSettings.addAction(self.actionModels_Setting)
        self.menuSettings.addAction(self.actionImage_Settings)
        self.menuSettings.addAction(self.menuDownload_Settings.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSelectImage.setText(_translate("MainWindow", "Select Image"))
        self.btnRender.setText(_translate("MainWindow", "Render"))
        self.btnDownload.setText(_translate("MainWindow", "Download"))
        self.label_5.setText(_translate("MainWindow", "Min Thick"))
        self.label_2.setText(_translate("MainWindow", "Shape"))
        self.label_3.setText(_translate("MainWindow", "Size"))
        self.label.setText(_translate("MainWindow", "Border"))
        self.label_6.setText(_translate("MainWindow", "Max Thick"))
        self.label_7.setText(_translate("MainWindow", "Other Setting"))
        self.label_8.setText(_translate("MainWindow", "Other Setting"))
        self.raidoBtnBorderYes.setText(_translate("MainWindow", "Yes"))
        self.raidoBtnBorderNo.setText(_translate("MainWindow", "No"))
        self.label_4.setText(_translate("MainWindow", "Other Setting"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuDownload_Settings.setTitle(_translate("MainWindow", "Download Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionDownloads.setText(_translate("MainWindow", "Downloads"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionBinary_STL.setText(_translate("MainWindow", "Binary STL"))
        self.actionASCII_STL.setText(_translate("MainWindow", "ASCII STL"))
        self.actionModels_Setting.setText(_translate("MainWindow", "Models Settings"))
        self.actionImage_Settings.setText(_translate("MainWindow", "Image Settings"))
        self.actionBinary_STL_2.setText(_translate("MainWindow", "Binary STL"))
        self.actionASCII_STL_2.setText(_translate("MainWindow", "ASCII STL"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
