DEFAULT_OUTPUT_NAME = 'temp_output.stl'
DEBUG_MODE = False

DEFAULT_CONFIG_SHAPE = 'Flat'
DEFAULT_CONFIG_SIZE = 300
MINIMUM_CONFIG_THICKNESS = 1
MAXIMUM_CONFIG_THICKNESS = 5
DEFAULT_CONFIG_CURVE = 0
DEFAULT_CONFIG_BORDER = False
DEFAULT_CONFIG_BORDER_THICKNESS = 0
DEFAULT_CONFIG_FORMAT = 'Binary'

